apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
# type: kubernetes.io/service-account-token
data:
  DB_USER: fadaG9fdazdsadsdfsdGdyZXM=
  DB_PASSWORD: VadfadafGfapacfad0lsdfazQVNlY3JldFBhc3N3b3Jkadfadfadf